Added secure_boot and affinity commands
vmware/vhpc-toolkit pull request #11
Opened 2022-06-28 18:26 UTC by Boredphilosopher96

2022-06-30 14:40 UTC, Michael870 requested changes

2022-06-30 14:40 UTC, Michael870 commented on vhpc_toolkit/get_args.py
> +        help="Secure boot on/off VM(s)",
Change help msg to "Turn secure boot on/off for VM(s)"

2022-06-30 14:40 UTC, Michael870 commented on vhpc_toolkit/get_args.py
> +        help="Name of the VM on which to NUMA node affinity",
Name of the VM on which to *change* NUMA node affinity

2022-06-30 14:40 UTC, Michael870 commented on vhpc_toolkit/get_args.py
> +    vm_affinity_group2 = vm_affinity_parser.add_mutually_exclusive_group(required=True)
This doesn't need to be a mutually exclusive group

2022-06-30 14:40 UTC, Michael870 commented on vhpc_toolkit/get_args.py
> +    numa_affinity_group2 = numa_affinity_parser.add_mutually_exclusive_group(
This doesn't need to be a mutually exclusive group

2022-06-30 14:40 UTC, Michael870 commented on README.md
> +pip install vhpc_toolkit
This doesn't work for me. Error msg below: 

(venv) xiaolongc-a02:vhpc-toolkit xiaolongc$ pip install -e vhpc_toolkit
Obtaining file:///Users/xiaolongc/Documents/vhpc_toolkit/github/vhpc-toolkit/vhpc_toolkit
ERROR: file:///Users/xiaolongc/Documents/vhpc_toolkit/github/vhpc-toolkit/vhpc_toolkit does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.

2022-06-30 14:40 UTC, Michael870 commented on vhpc_toolkit/get_args.py
> +    passthru_group1.add_argument(
Can we separate the code for passthru_host from this merge request?

2022-06-30 14:40 UTC, Michael870 commented on vhpc_toolkit/operations.py
> +    def change_affinity_cli(self, vm_name, affinity):
is this function obsolete?

2022-06-30 14:40 UTC, Michael870 commented on vhpc_toolkit/get_args.py
> +    vm_affinity_group2 = vm_affinity_parser.add_mutually_exclusive_group(required=True)
Actually, can we add another argument like "--clear" to clear the affinity?

2022-06-30 14:40 UTC, Michael870 commented on vhpc_toolkit/get_args.py
> +    numa_affinity_group2 = numa_affinity_parser.add_mutually_exclusive_group(
Same as above, add another argument --clear

2022-06-30 14:40 UTC, Michael870 commented on vhpc_toolkit/command.py
> +    elif ops.cfg[CMD_KEY] == "vm_scheduling_affinity":
Let's shorten this command to sched_affinity. The current one is too long and mess up with the help msg:

get_vm_config       View the performance metrics of the VM
    view                View the vCenter object names
    clone               Clone VM(s) via Full Clone or Linked Clone
    destroy             Destroy VM(s)
    power               Power on/off VM(s)
    secure_boot         Secure boot on/off VM(s)
    vm_scheduling_affinity
                        Change VM scheduling affinity
    numa_affinity       Change NUMA node affinity
    cpumem              Reconfigure CPU/memory for VM(s)

2022-07-11 20:32 UTC, Michael870 requested changes
Good job. At this point only a few minor changes are needed before you can merge.

2022-07-11 20:32 UTC, Michael870 commented on vhpc_toolkit/operations.py
> +                    "VM {0} is turned on. So cannot enable secure boot. Please turn off and try again".format(
"cannot enable secure boot" -> "cannot change secure boot"

2022-07-11 20:32 UTC, Michael870 commented on vhpc_toolkit/get_args.py
> +        help="Use '-' for ranges and ',' to separate values."
Use : for ranges

2022-07-11 20:32 UTC, Michael870 commented on vhpc_toolkit/get_args.py
> +        help="Use '-' for ranges and ',' to separate values."
same as above

2022-07-11 20:32 UTC, Michael870 commented on vhpc_toolkit/operations.py
> +    def numa_affinity_cli(self):
I think you also need to check for VM power on/off before the change

2022-07-11 21:53 UTC, Michael870 approved these changes

2022-07-11 22:21 UTC, Boredphilosopher96 reviewed
Merging

2022-07-11 22:22 UTC, merged