Enable sriov
vmware/vhpc-toolkit pull request #13
Opened 2022-07-12 18:32 UTC by Boredphilosopher96

2022-07-13 19:07 UTC, Michael870 requested changes
Most of the comments are on naming. Specifically, SRIOV is not limited to network, so let's change to device to be general. Also, although you see "location" used in some places, it's not common in HPC.

2022-07-13 19:07 UTC, Michael870 commented on vhpc_toolkit/command.py
> +    elif ops.cfg[CMD_KEY] == "modify_sriov":
Let's change the command to sriov_host

2022-07-13 19:07 UTC, Michael870 commented on vhpc_toolkit/get_args.py
> +        "This operation assumes that SR-IOV drivers have been installed on Esxi host",
ESXi

2022-07-13 19:07 UTC, Michael870 commented on vhpc_toolkit/get_args.py
> +        "--location",
Change the parameter to --device

2022-07-13 19:07 UTC, Michael870 commented on vhpc_toolkit/get_args.py
> +        help="Location of the pnic in format xxxx:xx:xx.x",
Location of the pnic -> Address of the device

2022-07-13 19:07 UTC, Michael870 commented on vhpc_toolkit/get_args.py
> +        help="Modify SR-IOV properties on host(s).\n"
properties -> configuration

2022-07-13 19:07 UTC, Michael870 commented on vhpc_toolkit/get_args.py
> +        "--on", action="store_true", help="Turn on SR-IOV mode for pnic on host(s)"
Device is not necessarily a pnic. Change "pnic" to "device"

2022-07-13 19:07 UTC, Michael870 commented on vhpc_toolkit/get_args.py
> +        "--off", action="store_true", help="Turn off SR-IOV mode for pnic on host(s)"
same as above

2022-07-13 19:07 UTC, Michael870 commented on vhpc_toolkit/get_args.py
> +    modify_sriov_parser.add_argument(
Add a default value of 4

2022-07-13 19:07 UTC, Michael870 commented on vhpc_toolkit/config_objs.py
> +        Function to enable/disable SRIOV and/or change the number of virtual functions on vmnics of a host.
vmnics -> devices

2022-07-13 19:07 UTC, Michael870 commented on vhpc_toolkit/config_objs.py
> +        pnic_location: str,
change this variable name to "device" or "device_id"

2022-07-15 18:13 UTC, qoofyk commented on vhpc_toolkit/get_args.py
> +        default=4,
remove default=4

2022-07-15 18:14 UTC, qoofyk commented on vhpc_toolkit/get_args.py
> +        help="Number of virtual functions. This argument is ignored if used with --off flag",
A warning message to users "num_func must be equal or smaller than the VF enabled in firmware"

2022-07-18 15:56 UTC, Michael870 commented on vhpc_toolkit/get_args.py
> +    modify_sriov_parser.add_argument(
The default should be to not change the value if user ignores it

2022-07-18 16:14 UTC, qoofyk commented on vhpc_toolkit/config_objs.py
> +                f"{'enabled' if enable_sriov else 'disabled'} SRIOV for network with location: {device_id} on host {self.host_obj.name}"
SRIOV for network with location --> SRIOV on network adapter with PCIe Device ID

2022-07-18 16:15 UTC, Michael870 requested changes

2022-07-18 16:15 UTC, Michael870 commented on vhpc_toolkit/operations.py
> +                self.cfg["location"],
location -> device

2022-07-18 16:15 UTC, Michael870 commented on vhpc_toolkit/config_objs.py
> +                f"{'enabled' if enable_sriov else 'disabled'} SRIOV for network with location: {device_id} on host {self.host_obj.name}"
network with location -> device

2022-07-18 16:18 UTC, qoofyk commented on vhpc_toolkit/config_objs.py
> +            device_id: Address of the device which supports SRIOV in format xxxx:xx:xx.x
device_id: PCIe address of the Virtual Function (VF) of the SRIOV device in format xxxx:xx:xx.x

2022-07-18 16:20 UTC, qoofyk commented on vhpc_toolkit/config_objs.py
> +            num_virtual_functions: Number of virtual functions to set for the NIC
num_virtual_functions: Number of virtual functions to set for the SRIOV device

2022-07-18 16:21 UTC, qoofyk commented on vhpc_toolkit/get_args.py
> +        help="Address of the SR-IOV device in format xxxx:xx:xx.x",
help="PCIe address of the Virtual Function (VF) of the SR-IOV device in format xxxx:xx:xx.x"

2022-07-18 16:26 UTC, qoofyk commented on vhpc_toolkit/config_objs.py
> +                f"{'enabled' if enable_sriov else 'disabled'} SRIOV for network with location: {device_id} on host {self.host_obj.name}"
network with location --> PCIe device

2022-07-18 17:48 UTC, qoofyk commented on vhpc_toolkit/get_args.py
> +        default=4,
Delete this comment

2022-07-18 17:50 UTC, qoofyk approved these changes

2022-07-18 17:58 UTC, Michael870 commented on vhpc_toolkit/config_objs.py
> +                f"{'enabled' if enable_sriov else 'disabled'} SRIOV for network with location: {device_id} on host {self.host_obj.name}"
Sumukh, please double check my comment above. The request is replace three words

2022-07-19 17:38 UTC, Michael870 approved these changes

2022-07-19 17:56 UTC, merged